# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service
ioc-instance:

  image: ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.4.1
