# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/repo
# default values for all IOCs on bl02t
ioc-instance:

  # the beamline name - only set for beamlines
  beamline: bl02t

  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: false

  image: ""

  dataVolume:
    pvc: true
    hostPath: /data
